ChargeBackCalculation/Models/ComplaintRegister.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ChargeBackCalculation.Models
{
    public class ComplaintRegister
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = " Customer id is Required")]
        [Display(Name = "Customer Id")]
        public int CustomerId { get; set; }

        [Required(ErrorMessage = " First Name is Required")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = " Last Name is Required")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "You must provide a phone number")]
        [Display(Name = "Contact Number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Email ID")]
        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress(ErrorMessage = "Invalid Email Address.")]
        public string Email { get; set; }

        [Required(ErrorMessage = " Account no is Required")]
        [StringLength(11)]
        public string BankAccountNo { get; set; }

        [Required(ErrorMessage = " Bank Branch is Required")]
        public string BankBranch { get; set; }

        [Required(ErrorMessage = " First Name is Required")]
        [Display(Name = "Charge Back Amount")]
        public string ChargeBackAmount { get; set; }

        [Required(ErrorMessage = " Reason is Required")]
        public string Reason { get; set; }

        [Required]
        [Display(Name = "Date Of Transaction")]
        [DataType(DataType.Date)]
        public DateTime? DateOfTransaction { get; set; }

    }
}

ChargeBackCalculation/Controllers/ComplaintRegistersController.cs
using ChargeBackCalculation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChargeBackCalculation.Controllers
{
    public class ComplaintRegistersController : Controller
    {
        private UserLoginDbContext db = new UserLoginDbContext();
        // GET: ComplaintRegisters
        public ActionResult Index()
        {
            return View(db.ComplaintRegisters.ToList());
        }


        public ActionResult Create()
        {
            return View();
        }
        public ActionResult LogOut()
        {
            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CustomerId,FirstName,LastName,PhoneNumber,Email,BankAccountNo,BankBranch,ChargeBackAmount,Reason,DateOfTransaction")] ComplaintRegister complaintregister, int customerid)
        {
            if (ModelState.IsValid)
            {

                var user = db.CustomerRegisters.Where(x => x.UserId == customerid).FirstOrDefault();
                if (user != null)
                {
                    var user1 = db.Employees.Where(x => x.CustomerId == customerid).FirstOrDefault();
                    if (user1 != null)
                    {
                        db.ComplaintRegisters.Add(complaintregister);
                        db.SaveChanges();
                        TempData["Message"] = "Complaint Lodged Successfully ";
                        //return RedirectToAction("Index");
                    }
                    else
                    {

                        return View(complaintregister);


                    }
                }
            }

            return View(complaintregister);
        }
    }
}

ChargeBackCalculation/Views/ComplaintRegisters/Create.cshtml
@model ChargeBackCalculation.Models.ComplaintRegister

@{ ViewBag.Title = "Create"; }

<h2>CustomerComplaint</h2>
@Html.ActionLink("Logout", "LogOut", "ComplaintRegisters", null, new { @class = "nav-link" })
@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Customer</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CustomerId, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.BankAccountNo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BankAccountNo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.BankAccountNo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.BankBranch, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BankBranch, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.BankBranch, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ChargeBackAmount, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ChargeBackAmount, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ChargeBackAmount, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Reason, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Reason, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Reason, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DateOfTransaction, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DateOfTransaction, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DateOfTransaction, "", new { @class = "text-danger" })
                        </div>
                        @*<div class="form-group">
                                @Html.LabelFor(model => model.Days, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Days, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Days, "", new { @class = "text-danger" })
                                </div>
                            </div>*@
                    </div>
                </div>
                                <html>

                                <body>
                                    <table>
                                        <tr>
                                            <td>
                                                @using (Html.BeginForm("Create", "ComplaintRegisters", FormMethod.Post))
                                                {
                                <input type="submit" id="btnSave" value="RegisterComplaint" />}
                                            </td>
                                        </tr>
                                    </table>
                                    @if (TempData["Message"] != null)
                                    {
                    <script type="text/javascript">
            window.onload = function () {
                alert('@TempData["Message"]');
            };
                    </script>}
                                </body>
                            </html> @*<div class="form-group">
                                                    <div class="col-md-offset-2 col-md-10">
                                                        <input type="submit" value="Create" class="btn btn-default" />
                                                    </div>
                                                </div>*@}

ChargeBackCalculation/Views/ComplaintRegisters/Index.cshtml
@model IEnumerable<ChargeBackCalculation.Models.ComplaintRegister>
@{ ViewBag.Title = "Index"; }

<h2>Index</h2>
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">

        <li class="nav-item" style="text-align:right">
            @Html.ActionLink("Logout", "LogOut", "ComplaintRegisters", null, new { @class = "nav-link" })
        </li>
    </ul>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BankAccountNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BankBranch)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ChargeBackAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Reason)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfTransaction)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.Days)
            </th>*@
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.CustomerId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FirstName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LastName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PhoneNumber)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.BankAccountNo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.BankBranch)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ChargeBackAmount)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Reason)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DateOfTransaction)
    </td>

    @*<td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>*@
</tr>
}

</table>